### ISSUE TITLE
Can't add tracks to new sets, except from nowplaying 'add to' button

### ISSUE THREAD

**Issue by zbeekman** [martindale/soundtrack.io#118]
Steps to recreate:
1. Create a brand new set (either from set management or by trying to add a song from it's song page to new set)
2. If created the set from the set management page, try to add a song from the song's page to that set.
3. If you try to create a new set containing a song from the song's page with the same name as a new empty set, then it will create an additional empty set of the same name.

On  Chrome on Mac, latest release of both, OSX 10.10 IIRC

**Comment by martindale** [comment]
So, track additions work from the main index, but not from any other page?  After a single track has been added, do the other pages function?

**Comment by zbeekman** [comment]
I think your understanding is correct. This works: ![screen shot 2015-01-12 at 10 07 33 am](https://cloud.githubusercontent.com/assets/279612/5704843/fc934792-9a42-11e4-885a-8fbe697ce200.png)

But then, say from the play history I see this: 
![screen shot 2015-01-12 at 10 09 42 am](https://cloud.githubusercontent.com/assets/279612/5704880/2b36756a-9a43-11e4-9761-e4da94db5df7.png)

Notice that only the my ‘EDM' set is available for additions, not ‘Lose your $hit’ or ’test set’

Furthermore, I can then enter a new set 
![screen shot 2015-01-12 at 10 10 49 am](https://cloud.githubusercontent.com/assets/279612/5704901/514255c6-9a43-11e4-829e-debc679f8e40.png)

And the set is created, but the song in question isn’t added:
![screen shot 2015-01-12 at 10 11 46 am](https://cloud.githubusercontent.com/assets/279612/5704923/73828e08-9a43-11e4-9c40-99c428be3e2a.png)

![screen shot 2015-01-12 at 10 12 33 am](https://cloud.githubusercontent.com/assets/279612/5704933/8dda52c2-9a43-11e4-9a14-e329d94aaa0f.png)
