### ISSUE TITLE
chat timestamps no longer show song that was playing

### ISSUE THREAD

**Issue by zbeekman** [martindale/soundtrack.io#119]
minor issue

**Comment by martindale** [comment]
What browser?  Working for me in Chrome 39.0.2171.95:

![](https://dl.dropbox.com/s/uo4900rojfuspef/Screenshot%202015-01-07%2012.40.42.png?dl=0)

**Comment by zbeekman** [comment]
OK.... I'm an idiot/too impatient. I wasn't waiting long enough for the roll-over effect my bad.
