### ISSUE TITLE
Ability of room creator to edit room name/description or delete room

### ISSUE THREAD

**Issue by zbeekman** [martindale/soundtrack.io#131]
Currently, once a room is created there is no way to edit its name/description or to delete it. Not sure about the internals, but may need UUIDs to track things like rooms and users and sets, to allow their names to be edited.

**Comment by ROBOTunderscore** [comment]
Can I request an admin to edit my room description manually? I accidentally made the description of my room have gigantic text and it's unfair to the other rooms on the homepage.

**Comment by martindale** [comment]
@ROBOTunderscore I'm going to prioritize a simple editing feature for today.  Thanks for your willingness to change your room's description either way!

**Comment by ROBOTunderscore** [comment]
You might want to disable markdown in room descriptions altogether (aside from URLs and line breaks) if you can. Other people will probably abuse it.

**Comment by martindale** [comment]
The above pull request adds support for room owners editing their own rooms' descriptions (and also disables markdown).  It's a hack using the old Maki 0.1 methods, but it'll let you edit your room for now.

I've also already deployed it to soundtrack.io, so you should now have an "edit" button on the index page for any room you own.
