### ISSUE TITLE
Bandcamp integration causing track advance issues

### ISSUE THREAD

**Issue by unusualbob** [martindale/soundtrack.io#138]
In some cases `item` is null at [this line](https://github.com/martindale/soundtrack.io/blob/soundtrack.io/public/js/app.js#L431) resulting in:

```
Uncaught TypeError: Cannot read property 'data' of null app.js:431
  (anonymous function) app.js:428
  soundtrack.sockjs.onmessage sockjs-0.3.min.js:27
  d.dispatchEvent sockjs-0.3.min.js:27
  y._dispatchMessage sockjs-0.3.min.js:27
  y._didMessagesockjs-0.3.min.js:27 e.ws.onmessage
```
This error stops code execution, resulting in a non-advancing track.

**Comment by martindale** [comment]
@chrisinajar would you mind taking a look at this one?

**Comment by unusualbob** [comment]
I will point out  I haven't seen this bug in a while I don't think. I was seeing it like every 10th track when I reported it.

**Comment by martindale** [comment]
I might have inadvertently fixed this when troubleshooting another issue.  Re-open if it continues.
