### ISSUE TITLE
s.io seems to be down

### ISSUE THREAD

**Issue by zbeekman** [martindale/soundtrack.io#144]
```
An error has occurred: {“code”:"ECONNREFUSED","errno":"ECONNREFUSED","syscall":"connect"}
```

**Comment by martindale** [comment]
Fixed.  Issue with startup for rooms with empty histories.  Patch incoming.

**Comment by zbeekman** [comment]
FYI this was for the entire site... but it works now, so maybe the patch fixed it?

**Comment by martindale** [comment]
Yes, the server was waiting to listen for HTTP connections because several rooms' queues couldn't be initialized.  I just start the server anyways, now.
