### ISSUE TITLE
Toggle Video Button none responsive #Bug

### ISSUE THREAD

**Issue by mikemimik** [martindale/soundtrack.io#41]
`Line 580: if (parseInt($('#messages').css('height')) != 230) {` doesn't seem to evaluate correctly on my machine (chrome/OSX).

The button is non responsive when I try and use it.

Notes:
When I change the `if statement` from above to this:
`if (parseInt($('#messages').css('height')) == 230) {` the statement evaluates and my video toggles off and I have a full chat screen. This however breaks the `else` statement and I can't toggle the video back in.

I am pretty sure I can fix the logic of this statement though I'm unsure as to how it broke in the first place.

**Comment by martindale** [comment]
Closing this, as it is resolved!
