### ISSUE TITLE
Broken Bio Page #Bug

### ISSUE THREAD

**Issue by mikemimik** [martindale/soundtrack.io#43]
Hey so by accident I managed to break the bio page for myself. It has to do with the way the pages are rendered with the information you put into the textbox.

Current broken page:
https://docs.google.com/file/d/0B6dAeVdSmX3-R0NBMkp6aVZEekU/

Inspected Elements:
https://docs.google.com/file/d/0B6dAeVdSmX3-N1NjVUdWTVppbVE

As you can see the html code is still there but it's stuck inside the `<style>` tag I tried to add to mark up the page a little.

I would image that @martindale would simply have to remove my bio from the database and it would reset everything back to normal. 

Issue being that anyone can do this and break the bio page.

**Comment by martindale** [comment]
Hey there, can you take another look at this?  It's been open a while, but I do suspect there is still an issue.

**Comment by mikemimik** [comment]
Markdown works in bio and it's also properly sanitized.
