### ISSUE TITLE
restler broken in nodejs v0.10.x

### ISSUE THREAD

**Issue by fractaloop** [martindale/soundtrack.io#6]
Restler has an existing issue https://github.com/danwrong/restler/issues/110 that prevents launch in nodejs v0.10.x.

A workaround exists as the moment at https://github.com/danwrong/restler/pull/113#issuecomment-18813431

**Comment by martindale** [comment]
Closing, as I am able to run the current version of soundtrack with 0.10.  Please open a new issue if you encounter further problems.
